
services:
  db:
    image: mariadb:10.11
    restart: always
    command: --transaction-isolation=READ-COMMITTED
    volumes:
      - ./db_data:/var/lib/mysql  # 로컬 디렉토리 ./db_data를 컨테이너 내부 /var/lib/mysql에 마운트
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud
    restart: always
    ports:
      - 9090:80
    depends_on:
      - redis
      - db
    volumes:
      - ./nextcloud_data:/var/www/html  # 로컬 디렉토리 ./nextcloud_data를 컨테이너 내부 /var/www/html에 마운트
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

volumes: {}  # 기존 Docker 볼륨 사용 안 함
