version: "3.9"
services:
  elasticsearch-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elasticsearch-1
    environment:
      - node.name=elasticsearch-1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-2,elasticsearch-3
      - cluster.initial_master_nodes=elasticsearch-1,elasticsearch-2,elasticsearch-3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch-1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - network-docker-devtool

  elasticsearch-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elasticsearch-2
    environment:
      - node.name=elasticsearch-2
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-1,elasticsearch-3
      - cluster.initial_master_nodes=elasticsearch-1,elasticsearch-2,elasticsearch-3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch-2:/usr/share/elasticsearch/data
    networks:
      - network-docker-devtool

  elasticsearch-3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elasticsearch-3
    environment:
      - node.name=elasticsearch-3
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch-1,elasticsearch-2
      - cluster.initial_master_nodes=elasticsearch-1,elasticsearch-2,elasticsearch-3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch-3:/usr/share/elasticsearch/data
    networks:
      - network-docker-devtool

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch-1:9200"]
    depends_on:
      - elasticsearch-1
      - elasticsearch-2
      - elasticsearch-3
    networks:
      - network-docker-devtool

  logstash:
    image: docker.elastic.co/logstash/logstash:8.2.2
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - kibana
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./data/logstash-data:/usr/share/logstash/data
      - ./data/logstash-logs:/usr/share/logstash/logs
    networks:
      - network-docker-devtool

networks:
  network-docker-devtool:
    name: network-docker-devtool