version: "3.9"
services:
  web:
    image: tomcat:latest
    ports:
      - 8080
    deploy:
      replicas: 5
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    volumes:
      - ./www/:/usr/local/tomcat/webapps/ROOT
  lb:
    image: nginx:latest
    ports:
      - 20800:80
    volumes: 
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - web
    command: [nginx-debug, '-g', 'daemon off;']